### ISSUE TITLE
OAuth Authentication failing.

### ISSUE THREAD

**Issue by wisesabre** [yammer/ios-yammer-sdk#10]
After a successful login, ```[[YMLoginClient sharedInstance] handleLoginRedirectFromUrl:url sourceApplication:sourceApplication]``` is being called. 

and it tries to get OAuth token (https://www.yammer.com/oauth2/access_token.json) Which is failing right now. 

response: Request failed: forbidden (403)

**Comment by pwillsey** [comment]
Thanks for the report we'll look into this

**Comment by pwillsey** [comment]
I'm not having this problem, so it's probably network specific, can you confirm that you have third party apps enabled on your primary network ? You might need an admin to check this for you.

**Comment by wisesabre** [comment]
You are right, I'm having this issue because my app isnt global and im trying to post on some other network. 

To make it  "Global" seems like i need to contact "help desk". I've googled for "help desk" but cant find anything. after that I called Microsoft helpline the support officer asked me "what is Yammer?" :-/ 

I'll appreciate if you could guide me to right direction.

**Comment by gwlove** [comment]
Hey Saqib, shoot an email over to yammerplatform@microsoft.com with your app ID and we'll help you out here. To get your app ID, head to https://www.yammer.com/client_applications/, click on your app and send us the five digit number at the end of the URL.
