### ISSUE TITLE
Yammer login won't zoom out

### ISSUE THREAD

**Issue by joeboyscout04** [yammer/ios-yammer-sdk#19]
This may be a webpage issue, but I'm seeing that the yammer login page is partially cut off.  I can't zoom in on it. 

![simulator screen shot apr 1 2016 13 35 49](https://cloud.githubusercontent.com/assets/1489809/14215105/ed880118-f80e-11e5-9903-ac88c4f38116.png)

**Comment by joelklabo** [comment]
Looks like you got this fixed 👍

**Comment by joeboyscout04** [comment]
I fixed it on my own fork but I haven't deployed this to production because I wanted see if you could come up with something better.  It's really an issue with the HTML/JS on the login page, since we see this same issue on Android devices and mobile safari.  My "fix" is really just a workaround.

**Comment by pwillsey** [comment]
We're going to post a bug to the front-end team here and see if we can get this fixed
